namespace: workshop
repo: go-demo
name: init_infra_on_tke
desc: ''
timeout: 60
env:
    -
        name: _WORKFLOW_FLAG_HUB_TOKEN
        value: 'true'
stages:
    -
        name: init_infra
        desc: ''
        sequencing: sequence
        type: normal
        jobs:
            -
                name: create_common_mysql
                component: 'hub.tencentyun.com/workshop/init-infrastructure:latest'
                allow_failure: false
                retry: 0
                when: ''
                inputs:
                    -
                        name: TKE_SERVER
                        value: 'https://cls-********.ccs.tencent-cloud.com'
                    -
                        name: TKE_PASSWORD
                        value: 52o***************************4x
                    -
                        name: TKE_USERNAME
                        value: admin
                    -
                        name: TKE_MYSQL_NODE_NAME
                        value: 172.27.100.24
                    -
                        name: MYSQL_ROOT_PASSWORD
                        value: '123456'
                    -
                        name: TKE_CERTIFICATE
                        value: >-
                            -----BEGIN CERTIFICATE-----
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ****************************************************************
                            ************

                            -----END CERTIFICATE-----

