apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-web
  labels:
    app: go-demo-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demo-web
  template:
    metadata:
      labels:
        app: go-demo-web
    spec:
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: go-demo-config
      containers:
      - name: go-demo
        image: "{{docker_image}}" # hub.tencentyun.com/workshop/go-demo # TODO from args
        command: ["/go-demo"]
        args: ["serve", "-c /etc/go-demo/config.yaml"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: go-demo-config
          mountPath: /etc/go-demo

# kubectl create configmap go-demo-config --from-file=config/ -n test
# kubectl create configmap go-demo-config --from-file=config/ -n prod

